<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FP3M7NI" failures="1" tests="2" name="runner.Runner" time="45.997" errors="0" timestamp="2025-01-17T12:03:42 GMT-08:00" skipped="0">
  <testcase classname="runner.Runner" name="runScenario" time="19.705"/>
  <testcase classname="runner.Runner" name="runScenario" time="26.292">
    <failure message="expected [success] but found [failure]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [success] but found [failure]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.LoginTest.User_should_be_able_to_login_based_on_expected_login_status(LoginTest.java:114)
at âœ½.User should be able to login based on "success" login status(file:///C:/Users/Admin/eclipse-workspace/CucumberBDDFramework/src/test/java/features/login.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.Runner -->
